name: visiosense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  firebase_core_web: ^2.18.1
  intl_phone_field: ^3.0.1
  url_launcher: ^6.0.20
  sleek_circular_slider: ^2.0.1
  uuid: ^3.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  mailer: ^6.2.0
  flutter_email_sender: ^6.0.3
  cloud_functions: ^5.1.3
  flutter_launcher_icons: ^0.14.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.9
  mqtt_client: ^10.5.1
  geolocator: ^12.0.0
  tflite: ^1.1.2
  flutter_tts: ^4.0.2
   


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/blind.png
    - assets/waveformnew.png
    - assets/forgetpassword.png
    - assets/resetpasswordnew.png
    - assets/verificationnew.png
    - assets/logo.jpg
    - assets/wave.png
    - assets/aboutapp.jpg
    - assets/google.jpg
    - assets/privacy.jpg
    - assets/t&c.jpg
    - assets/model.tflite
    - assets/labels.txt
